bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300

databases 16
save ""
appendonly no

maxmemory 256mb
maxmemory-policy allkeys-lfu
maxmemory-samples 10

lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes

loglevel notice

rename-command FLUSHALL ""
rename-command CONFIG ""
rename-command DEBUG ""
